# Exported from Render on 2025-11-16T14:22:27Z
version: "1"
services:

- type: web
  name: Next Bus (Stable)
  runtime: python
  repo: https://github.com/Sourish-Kanna/Next-Bus-Backend
  branch: stable
  plan: free
  envVars:
  - key: ORIGIN_LIST
    sync: false
  - key: FIREBASE_CREDENTIALS_JSON
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  autoDeployTrigger: commit

- type: web
  name: Next Bus (Development)
  runtime: python
  repo: https://github.com/Sourish-Kanna/Next-Bus-Backend
  plan: free
  envVars:
  - key: ORIGIN_LIST
    sync: false
  - key: DEV_ENV
    sync: false
  - key: FIREBASE_CREDENTIALS_JSON
    sync: false
  region: oregon
  buildCommand: 'pip install -r requirements.txt '
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  autoDeployTrigger: commit
